import { Category, Product } from "../types";

export const categories: Category[] = [
  {
    id: 1,
    name: "Mobiles",
    icon: "📱",
  },
  {
    id: 2,
    name: "Fashion",
    icon: "👕",
  },
  {
    id: 3,
    name: "Electronics",
    icon: "💻",
  },
  {
    id: 5,
    name: "Beauty",
    icon: "🧴",
  },
];

export const trendingProducts: Product[] = [
  {
    id: 1,
    name: "Apple iPhone 15",
    description: "Apple smartphone with advanced performance.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "Apple",
    price: 69999,
    originalPrice: 79900,
    discountPercentage: 12,
    rating: 2.8,
    reviews: 18,
    image: "📱",
    badge: "BESTSELLER",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    description: "Premium Samsung smartphone.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "Samsung",
    price: 74999,
    originalPrice: 81999,
    discountPercentage: 9,
    rating: 1.7,
    reviews: 11,
    image: "📱",
  },
  {
    id: 3,
    name: "OnePlus 12R",
    description: "Powerful OnePlus smartphone.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "OnePlus",
    price: 39999,
    originalPrice: 44999,
    discountPercentage: 11,
    rating: 3.6,
    reviews: 14,
    image: "📱",
  },
  {
    id: 4,
    name: "Google Pixel 9",
    description: "Google Pixel smartphone.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "Google",
    price: 79999,
    originalPrice: 89999,
    discountPercentage: 11,
    rating: 4.8,
    reviews: 21,
    image: "📱",
  },
  {
    id: 5,
    name: "iPhone 15 Pro",
    description: "Premium Apple smartphone.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "Apple",
    price: 129999,
    originalPrice: 139999,
    discountPercentage: 7,
    rating: 1.9,
    reviews: 32,
    image: "📱",
  },
  {
    id: 6,
    name: "Samsung Galaxy A55",
    description: "Samsung mid-range smartphone.",
    category: "Mobiles",
    subCategory: "Smartphones",
    brand: "Samsung",
    price: 34999,
    originalPrice: 39999,
    discountPercentage: 12,
    rating: 2.5,
    reviews: 25,
    image: "📱",
  },
  {
    id: 7,
    name: "MacBook Air M3",
    description: "Lightweight Apple laptop for work and study.",
    category: "Electronics",
    subCategory: "Laptops",
    brand: "Apple",
    price: 114999,
    originalPrice: 124999,
    discountPercentage: 8,
    rating: 3.8,
    reviews: 27,
    image: "💻",
    badge: "TRENDING",
  },
  {
    id: 8,
    name: "Samsung Galaxy Book4",
    description: "Slim Samsung laptop with a bright display.",
    category: "Electronics",
    subCategory: "Laptops",
    brand: "Samsung",
    price: 84999,
    originalPrice: 94999,
    discountPercentage: 11,
    rating: 2.5,
    reviews: 16,
    image: "💻",
  },
  {
    id: 9,
    name: "iPad Air",
    description: "Powerful Apple tablet for creativity and entertainment.",
    category: "Electronics",
    subCategory: "Tablets",
    brand: "Apple",
    price: 59999,
    originalPrice: 64999,
    discountPercentage: 8,
    rating: 4.7,
    reviews: 22,
    image: "📲",
  },
  {
    id: 10,
    name: "OnePlus Pad 2",
    description: "Fast OnePlus tablet with a smooth high-refresh display.",
    category: "Electronics",
    subCategory: "Tablets",
    brand: "OnePlus",
    price: 39999,
    originalPrice: 44999,
    discountPercentage: 11,
    rating: 1.6,
    reviews: 19,
    image: "📲",
  },
  {
    id: 11,
    name: "Apple Magic Keyboard",
    description: "Compact wireless keyboard for Apple devices.",
    category: "Electronics",
    subCategory: "Accessories",
    brand: "Apple",
    price: 9999,
    originalPrice: 11999,
    discountPercentage: 17,
    rating: 1.4,
    reviews: 13,
    image: "⌨️",
  },
  {
    id: 12,
    name: "Samsung Galaxy Buds3",
    description: "Wireless Samsung earbuds with active noise cancellation.",
    category: "Electronics",
    subCategory: "Accessories",
    brand: "Samsung",
    price: 12999,
    originalPrice: 14999,
    discountPercentage: 13,
    rating: 2.3,
    reviews: 17,
    image: "🎧",
  },
  {
    id: 13,
    name: "Nike Air Max 270",
    description: "Cushioned everyday sneakers with a breathable design.",
    category: "Fashion",
    subCategory: "Footwear",
    brand: "Nike",
    price: 8999,
    originalPrice: 10999,
    discountPercentage: 18,
    rating: 4.6,
    reviews: 34,
    image: "👟",
    badge: "TRENDING",
  },
  {
    id: 14,
    name: "Adidas Essentials Hoodie",
    description: "Soft cotton-blend hoodie for comfortable everyday wear.",
    category: "Fashion",
    subCategory: "Clothing",
    brand: "Adidas",
    price: 2499,
    originalPrice: 3499,
    discountPercentage: 29,
    rating: 4.4,
    reviews: 26,
    image: "👕",
  },
  {
    id: 15,
    name: "Nike Everyday Backpack",
    description: "Durable laptop backpack with spacious storage.",
    category: "Fashion",
    subCategory: "Bags",
    brand: "Nike",
    price: 2999,
    originalPrice: 3999,
    discountPercentage: 25,
    rating: 4.3,
    reviews: 18,
    image: "🎒",
  },
  {
    id: 16,
    name: "Sony WH-1000XM5",
    description: "Premium wireless headphones with active noise cancellation.",
    category: "Electronics",
    subCategory: "Audio",
    brand: "Sony",
    price: 26999,
    originalPrice: 34990,
    discountPercentage: 23,
    rating: 4.8,
    reviews: 41,
    image: "🎧",
    badge: "BESTSELLER",
  },
  {
    id: 17,
    name: "Canon EOS R50",
    description: "Compact mirrorless camera for photos and video.",
    category: "Electronics",
    subCategory: "Cameras",
    brand: "Canon",
    price: 64999,
    originalPrice: 72999,
    discountPercentage: 11,
    rating: 4.7,
    reviews: 15,
    image: "📷",
  },
  {
    id: 18,
    name: "Lakme Absolute Skin Dew Serum",
    description: "Hydrating face serum for a fresh, glowing look.",
    category: "Beauty",
    subCategory: "Skincare",
    brand: "Lakme",
    price: 699,
    originalPrice: 899,
    discountPercentage: 22,
    rating: 4.5,
    reviews: 29,
    image: "🧴",
  },
  {
    id: 19,
    name: "Maybelline Fit Me Foundation",
    description: "Lightweight foundation with a natural matte finish.",
    category: "Beauty",
    subCategory: "Makeup",
    brand: "Maybelline",
    price: 549,
    originalPrice: 699,
    discountPercentage: 21,
    rating: 4.4,
    reviews: 37,
    image: "💄",
  },
  {
    id: 20,
    name: "Lakme Nourish Hair Mask",
    description: "Nourishing hair mask for smooth, manageable hair.",
    category: "Beauty",
    subCategory: "Haircare",
    brand: "Lakme",
    price: 449,
    originalPrice: 599,
    discountPercentage: 25,
    rating: 4.2,
    reviews: 21,
    image: "🧴",
  },
];

export const productRating = [4, 3, 2, 1];
